name: Hajari CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: Convert image name
        id: image_name
        run: |
          echo "LOWERCASE_IMAGE_NAME=$(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set environment tag
        id: envtag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "ENV_TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "ENV_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image_name.outputs.LOWERCASE_IMAGE_NAME }}:${{ steps.envtag.outputs.ENV_TAG }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            